[package]
name = "favdir"
version = "0.1.0"
authors = ["avjves"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
structopt = "0.3.13"
dirs = "2.0.2"
